apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: core
  namespace: argocd
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: open-cluster-management.io/cluster-name
              operator: NotIn
              values:
                - hub
                - indernal
                - dev 
                - prod


