apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls
  namespace: whoami
spec:
  secretName: whoami-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  commonName: whoami.local
  dnsNames:
    - whoami.local
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
