apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            target_label: __address__
            regex: (.*):10250
            replacement: $1:10250
            
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: endpointslice
        relabel_configs:
          # Keep only services with a `prometheus.io/scrape` annotation set to "true".
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Use the service name as the job name.
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: job
          # Use the service port name for relabeling.
          - source_labels: [__meta_kubernetes_endpointslice_port_name]
            action: replace
            target_label: endpoint
          # Use the annotated metrics path if it exists.
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Use the annotated scheme if it exists.
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)