apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }
    
    loki.source.kubernetes "pod_logs" {
      // Use the output of the discovery component as the targets to scrape from.
      targets = discovery.kubernetes.pods.targets
    
      relabel_rules {
        labeldrop = ["__meta_kubernetes_pod_container_id"]
        labelmap  = "__meta_kubernetes_pod_label_(.*)"
      }
      
      // All logs from this source will be processed by the loki_pipeline.
      forward_to = [loki.process.loki_pipeline.receiver]
    }
    
    // This component processes logs from multiple sources before sending them to Loki.
    loki.process "loki_pipeline" {
      // All processed logs are forwarded to the Loki write component.
      forward_to = [loki.write.loki_push.receiver]
      
      stage {
        drop {
          drop = true
          labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_managed_by"]
        }
      }
    }
    
    // This component writes logs to the Loki API.
    loki.write "loki_push" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
    
    // This component scrapes Prometheus metrics from the discovered pods.
    prometheus.scrape "pod_metrics" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [prometheus.remote_write.prom_push.receiver]
    }
    
    // This component writes Prometheus metrics to the Prometheus remote write endpoint.
    prometheus.remote_write "prom_push" {
      endpoint {
        url = "http://prometheus:9090/api/v1/write"
      }
    }
    
    // This component receives telemetry data via the OTLP protocol.
    otelcol.receiver.otlp "otel_receiver" {
      grpc = {
        endpoint = "0.0.0.0:4317",
      }
      http = {
        endpoint = "0.0.0.0:4318",
      }
      
      output {
        // Logs received via OTLP are also routed through the loki_pipeline.
        logs = [loki.process.loki_pipeline.receiver]
      }
    }
