apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    discovery.kubernetes.pods "pods" {
      role = "endpoints"
    }
    
    loki.source.kubernetes "pod_logs" {
      targets = discovery.kubernetes.pods.pods.targets
    
      relabel_rules {
        labeldrop = ["__meta_kubernetes_pod_container_id"]
        labelmap  = "__meta_kubernetes_pod_label_(.*)"
      }
      
      forward_to = [loki.write.loki_push.receiver]
    }
    
    loki.write "loki_push" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
    
    loki.process "loki_pipeline" {
      forward_to = [loki.write.loki_push.receiver]
      
      stage {
        drop {
          drop = true
          labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_managed_by"]
        }
      }
    }
    
    prometheus.scrape "pod_metrics" {
      targets    = discovery.kubernetes.pods.pods.targets
      forward_to = [prometheus.remote_write.prom_push.receiver]
    }
    
    prometheus.remote_write "prom_push" {
      endpoint {
        url = "http://prometheus:9090/api/v1/write"
      }
    }
    
    otelcol.receiver.otlp "otel_receiver" {
      grpc = {
        endpoint = "0.0.0.0:4317",
      }
      http = {
        endpoint = "0.0.0.0:4318",
      }
      
      output {
        logs = [loki.process.loki_pipeline.receiver]
      }
    }
