apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: hub-cluster-info
        labelSelector:
          matchExpressions:
            - key: open-cluster-management.io/cluster-name
              operator: NotIn
              values:
                - hub
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-infra'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Albert-LGTM/k8-test.git'
        targetRevision: HEAD
        path: gitops/infra/manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
