apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-{{name}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "28.x.x"
  destination:
    server: "{{destination.server}}"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  values:
    ports:
      web:
        expose: true
      websecure:
        expose: true
    dashboard:
      enabled: true
      traefikUrl: "https://{{name}}.{{domain-name}}"