- name: Initialize the hub cluster with Open Cluster Management (OCM)
  ansible.builtin.command: clusteradm init --wait
  delegate_to: "{{ groups['hub_cluster'][0] }}"
  run_once: true
  changed_when: true
  environment:
    KUBECONFIG: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"

- name: Generate the join token for spoke clusters
  ansible.builtin.command: clusteradm get token
  delegate_to: "{{ groups['hub_cluster'][0] }}"
  run_once: true
  register: join_token_output
  changed_when: false
  environment:
    KUBECONFIG: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"

- name: Extract the token from clusteradm output
  ansible.builtin.set_fact:
    ocm_token: "{{ (join_token_output.stdout | regex_search('token=(\\S+)', '\\1')) | first }}"
    cacheable: true

- name: Get hub API server public endpoint
  ansible.builtin.command: kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'
  delegate_to: "{{ groups['hub_cluster'][0] }}"
  register: hub_apiserver
  changed_when: false
  environment:
    KUBECONFIG: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"