apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      volumes:
        - name: grafana-datasource-config
          configMap:
            name: grafana-datasources
      containers:
        - name: grafana
          volumeMounts:
            - name: grafana-datasource-config
              mountPath: /etc/grafana/provisioning/datasources