---
- name: Automate 5-cluster Kubernetes deployment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    # - name: Run hub cluster setup role
    #   ansible.builtin.include_role:
    #     name: setup-hub

    # - name: Run spoke clusters setup role
    #   ansible.builtin.include_role:
    #     name: setup-spokes

    - name: Run Argo CD setup role
      ansible.builtin.include_role:
        name: setup-argocd

    - name: Finalize GitOps deployment
      ansible.builtin.debug:
        msg: |
          Setup complete!