  # gitops/apps/wazuh/prod/patch-values.yaml

  # Use an external OpenSearch instance
  externalIndexer:
    enabled: true
    host: "https://db-opensearch-nyc1-70566-do-user-11835246-0.i.db.ondigitalocean.com"
    port: 25060

  # Disable the internal indexer
  indexer:
    enabled: false

  # Dashboard configuration
  dashboard:
    # Connect to the external OpenSearch
    host: "0.0.0.0"
    port: 5601
    opensearch:
      hosts: ["https://db-opensearch-nyc1-70566-do-user-11835246-0.i.db.ondigitalocean.com:25060"]
      ssl:
        verificationMode: none
      username: "doadmin"
      # Reference the secret key here
      passwordSecret:
        name: opensearch-creds
        key: opensearch-password

    # SSL termination handled by Traefik/Ingress
    server:
      ssl:
        enabled: false

    # Base URL routing
    uiSettings:
      overrides:
        defaultRoute: /app/wazuh

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    ingressClassName: "{{name}}-traefik"
    pathType: Prefix
    activeService: true
    hosts:
      - host: wazuh.cyberpartners.dk
        paths:
          - /
    tls:
      - secretName: vault-tls
        hosts:
          - wazuh.cyberpartners.dk
