---
- name: Run the OCM join command on all spoke clusters
  ansible.builtin.shell: >
    clusteradm join
    --hub-token '{{ ocm_token }}'
    --hub-apiserver {{ hub_apiserver.stdout }}
    --cluster-name '{{ item }}'
  environment:
    KUBECONFIG: "{{ hostvars[item].kubeconfig }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['spoke_clusters'] }}"
  register: join_output

- name: Accept cluster join request with retry
  ansible.builtin.shell: >
    clusteradm accept --clusters {{ item }}
  environment:
    KUBECONFIG: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"
  delegate_to: "{{ groups['hub_cluster'][0] }}"
  register: accept_output
  until: accept_output.rc == 0
  retries: 5
  delay: 10
  loop: "{{ groups['spoke_clusters'] }}"


