apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: calico-app-set
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-calico-app'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://docs.tigera.io/calico/charts'
        chart: tigera-operator
        targetRevision: 3.30.0
      destination:
        server: https://kubernetes.default.svc
        namespace: tigera-operator
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true