apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-cilium'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://helm.cilium.io/'
        chart: cilium
        targetRevision: 'v1.18.1'
        helm:
          values: |
            installCRDs: true
            ipam:
              mode: kubernetes
            hubble:
              enabled: true
            relay:
              enabled: true
            ui:
              enabled: true
            envoy:
              enabled: false
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true