apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-cilium'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      sources:
      - repoURL: 'https://helm.cilium.io/'
        chart: cilium
        targetRevision: 1.18.2
        helm:
          valueFiles:
          - $values/gitops/apps/cilium/{{name}}/values.yaml
      - repoURL: 'https://github.com/Albert-LGTM/k8-test.git'
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-sytem
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true