apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-applications
  namespace: argocd
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: hub-cluster-info
      labelSelector:
        matchExpressions:
          - key: "open-cluster-management.io/cluster-name"
            operator: NotIn
            values:
            - hub

  template:
    metadata:
      name: "{{name}}-infra"
    spec:
      project: default
      source:
        repoURL: https://github.com/Albert-LGTM/k8-test.git
        targetRevision: HEAD
        path: infra/manifests
      destination:
        server: "{{server}}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
