apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tailscale-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{name}}-tailscale"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      annotations:
        argocd.argoproj.io/skip-reconcile: "true"
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      sources:
      - repoURL: https://pkgs.tailscale.com/helmcharts
        chart: tailscale-operator
        targetRevision: 1.88.3
        helm:
          valueFiles:
          - $values/gitops/apps/tailscale/values.yaml
      - repoURL: 'https://github.com/Albert-LGTM/k8-test.git'
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: tailscale
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
