apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tailscale-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: core
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{name}}-tailscale"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      annotations:
        argocd.argoproj.io/skip-reconcile: "false"
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: kube-system
    spec:
      project: default
      sources:
      - repoURL: 'https://github.com/Albert-LGTM/k8-test.git'
        targetRevision: main
        path: gitops/apps/tailscale
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
