apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ticket-system-applications
  namespace: argocd
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: ocm-placement-generator
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: production
      requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-ticket-system'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      annotations:
        argocd.argoproj.io/skip-reconcile: "true"
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Albert-LGTM/k8-test.git'
        targetRevision: HEAD
        path: gitops/apps/ticket-system/overlays/production
      destination:
        server: https://kubernetes.default.svc
        namespace: ticket-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
