apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ticket-system-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-ts'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      annotations:
        argocd.argoproj.io/skip-reconcile: "true"
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://zammad.github.io/zammad-helm/
        chart: zammad
        targetRevision: 15.2.2
        helm:
          values: |
            zammadConfig:
              initJob:
                randomName: false
                annotations:
                  argocd.argoproj.io/hook: Sync 
      destination:
        server: https://kubernetes.default.svc
        namespace: ticket-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
