apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik-app-set
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-traefik-app'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/traefik/traefik-helm-chart.git'
        targetRevision: HEAD
        path: traefik
      destination:
        server: https://kubernetes.default.svc
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true