apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wazuh-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{name}}-wazuh"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      sources:
      - repoURL: https://morgoved.github.io/wazuh-helm
        chart: wazuh
        targetRevision: '4.12.0'
        helm:
          valueFiles:
          - $values/gitops/apps/wazuh/values.yaml
          - $values/gitops/apps/wazuh/{{name}}/patch-values.yaml
      - repoURL: 'https://github.com/Albert-LGTM/k8-test.git'
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
