apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: whoami-app-set
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-whoami-app'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://cowboysysop.github.io/charts/'
        chart: whoami
        targetRevision: 6.0.0
        helm:
          values: |
            ingress:
              enabled: true
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: web
              className: traefik
              hosts:
                - host: whoami.test.local
                  paths:
                    - path: /
                      pathType: Prefix
      destination:
        server: https://kubernetes.default.svc
        namespace: whoami
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true