apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: whoami-applications
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-whoami'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      annotations:
        argocd.argoproj.io/skip-reconcile: "true"
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/Albert-LGTM/k8-test.git"
        targetRevision: HEAD
        path: gitops/apps/services/whoami
      destination:
        server: https://kubernetes.default.svc
        namespace: whoami
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
