apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    # Ingestion limits and a wider timestamp tolerance.
    # We are increasing the rate limit to handle more logs.
    # The `ingestion_window` is increased to allow older logs to be accepted.
    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      reject_old_samples: false
      reject_old_samples_max_age: 168h # 7 days
    
    # Storage and ingestion settings.
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
        final_sleep: 0s
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m

    # These settings manage how Loki stores its data.
    # Updated to use the modern v13 schema and TSDB storage.
    schema_config:
      configs:
        - from: 2025-09-23
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
