apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3100'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: loki
  ports:
    - name: web
      port: 3100
      targetPort: 3100
