---
- name: Ensure the Argo CD namespace exists on hub
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace | default('argocd') }}"
    state: present
    kubeconfig: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"
  delegate_to: localhost

- name: Add the Argo Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-helm"
  delegate_to: localhost

- name: Install Argo CD via Helm (clean install, correct release name)
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: "{{ argocd_namespace | default('argocd') }}"
    create_namespace: true
    values:
      applicationset:
        enabled: true
      server:
        service:
          type: LoadBalancer
    kubeconfig: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"
  delegate_to: localhost

- name: Install OCM Argo CD add-on
  command: clusteradm install hub-addon --names argocd
  environment:
    KUBECONFIG: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"
  register: result
  failed_when: "'cannot re-use a name' not in result.stderr and result.rc != 0"
  changed_when: "'already exists' not in result.stdout"

- name: Enable Argo CD add-on on managed clusters
  command: clusteradm addon enable --names argocd --clusters {{ item | join(',') }}
  loop:
    - "{{ managed_clusters }}"
  environment:
    KUBECONFIG: "{{ hostvars[groups['hub_cluster'][0]].kubeconfig }}"
  register: addon_result